"""Dispatch Codex review once trusted CI reaches terminal success.

`codex-review.yml` is normally entered through `pull_request_target`, but a
Pull Request created and pushed by the repository's own `GITHUB_TOKEN` (as
`/implement` does) never fires that chain: GitHub does not run further
workflows for events generated by `GITHUB_TOKEN`. Without this reconciler,
such a Pull Request's exact head SHA never gets a Codex review after trusted
CI succeeds (see hane#80, which recovers from the hane#79 stall).

This script only decides *whether* and *for which exact head SHA* to request
a review; it does not perform the review itself and does not change
`codex-review.yml`'s authentication, permissions, or review contract.
"""
from __future__ import annotations

import datetime as dt
import json
import os
import re
import urllib.error
import urllib.request

TRUSTED_AUTHORS = {"hide212131", "github-actions[bot]", "claude[bot]"}
MAX_RESPONSE_BYTES = 8 * 1024 * 1024
IN_FLIGHT_SECONDS = 1200
GENERATION_PASSED = re.compile(r"^Trusted CI generation \S+ passed$")
REQUIRED_CI_CONTEXTS = (
    "cargo test / clippy (macos-latest)",
    "cargo test / clippy (windows-latest)",
)


class Unavailable(Exception):
    """Deliberately carries no server response, URL, token, or exception text."""


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def timestamp(value):
    if not isinstance(value, str):
        return None
    try:
        result = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
        return result if result.tzinfo else None
    except ValueError:
        return None


def latest_status(statuses, context):
    matches = [s for s in statuses if isinstance(s, dict) and s.get("context") == context]
    if not matches:
        return None
    return max(matches, key=lambda s: s.get("id") if isinstance(s.get("id"), int) else -1)


def decide(now, pr, statuses, repository, trusted_authors=TRUSTED_AUTHORS):
    """Return the reconciliation decision for one open Pull Request snapshot.

    `pr` is a GitHub `pulls` API object and `statuses` is that PR's exact
    head commit's status list (any order). The result is one of:

    - {"action": "skip", "reason": <str>}
    - {"action": "dispatch", "pr_number": <int>, "target_sha": <str>}

    This function never itself dispatches anything or re-checks the current
    head; the caller must re-verify the head SHA immediately before acting on
    a "dispatch" decision, since this snapshot can already be stale.
    """
    if not isinstance(pr, dict):
        return {"action": "skip", "reason": "malformed-pr"}

    head = pr.get("head") if isinstance(pr.get("head"), dict) else {}
    head_repo = ((head.get("repo") or {}).get("full_name") if isinstance(head.get("repo"), dict) else None)
    number = pr.get("number")
    head_sha = head.get("sha")
    author = (pr.get("user") or {}).get("login") if isinstance(pr.get("user"), dict) else None

    if (
        pr.get("state") != "open"
        or pr.get("draft") is not False
        or head_repo != repository
        or author not in trusted_authors
    ):
        return {"action": "skip", "reason": "not-eligible"}

    if type(number) is not int or not isinstance(head_sha, str) or not head_sha:
        return {"action": "skip", "reason": "malformed-pr"}

    if not isinstance(statuses, list):
        return {"action": "skip", "reason": "ci-not-terminal"}

    short_sha = head_sha[:12]

    generation = latest_status(statuses, "hane/trusted-ci-generation")
    if (
        generation is None
        or generation.get("state") != "success"
        or not GENERATION_PASSED.match(generation.get("description") or "")
    ):
        return {"action": "skip", "reason": "ci-not-terminal"}

    for context in REQUIRED_CI_CONTEXTS:
        job_status = latest_status(statuses, context)
        if job_status is None or job_status.get("state") != "success":
            return {"action": "skip", "reason": "ci-not-terminal"}

    codex = latest_status(statuses, "hane/codex-review")
    if codex is not None:
        codex_state = codex.get("state")
        codex_description = codex.get("description") or ""
        if codex_state == "success" and codex_description == f"Codex review clean for {short_sha}":
            return {"action": "skip", "reason": "already-reviewed"}
        if codex_state == "failure" and codex_description == f"Codex findings for {short_sha}":
            return {"action": "skip", "reason": "already-reviewed"}
        if codex_state == "pending":
            created = timestamp(codex.get("created_at"))
            if created is None or (now - created).total_seconds() < IN_FLIGHT_SECONDS:
                return {"action": "skip", "reason": "in-flight"}

        return {"action": "skip", "reason": "manual-recovery-required"}

    return {"action": "dispatch", "pr_number": number, "target_sha": head_sha}


class GitHubAPI:
    def __init__(self, repository: str, token: str):
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]*/[A-Za-z0-9_.-]+", repository) or not token:
            raise Unavailable()
        if repository.rsplit("/", 1)[-1] in {".", ".."}:
            raise Unavailable()
        self.root = "https://api.github.com/repos/" + repository
        self.token = token
        self.opener = urllib.request.build_opener(NoRedirect())

    def _headers(self):
        return {
            "Authorization": "Bearer " + self.token,
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "Hane-Codex-Review-Reconcile",
        }

    def get(self, suffix: str):
        request = urllib.request.Request(self.root + suffix, headers=self._headers())
        try:
            with self.opener.open(request, timeout=10) as response:
                raw = response.read(MAX_RESPONSE_BYTES + 1)
                if len(raw) > MAX_RESPONSE_BYTES:
                    raise Unavailable()
                return json.loads(raw), 'rel="next"' in response.headers.get("Link", "")
        except (OSError, ValueError, RecursionError, urllib.error.URLError):
            raise Unavailable() from None

    def pages(self, suffix: str, key: str | None = None):
        items = []
        for page in range(1, 6):
            separator = "&" if "?" in suffix else "?"
            data, more = self.get(suffix + separator + f"per_page=100&page={page}")
            batch = data.get(key) if key and isinstance(data, dict) else data
            if not isinstance(batch, list):
                raise Unavailable()
            items.extend(batch)
            if not more:
                return items
        raise Unavailable()

    def post(self, suffix: str, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        headers = self._headers()
        headers["Content-Type"] = "application/json"
        request = urllib.request.Request(self.root + suffix, data=body, headers=headers, method="POST")
        try:
            with self.opener.open(request, timeout=10) as response:
                response.read(MAX_RESPONSE_BYTES)
        except (OSError, urllib.error.URLError):
            raise Unavailable() from None


def run(api, repository, now, emit) -> int:
    try:
        prs = api.pages("/pulls?state=open")
    except Unavailable:
        emit("Pull Request 一覧を取得できないため今回は何もしません。")
        return 2

    exit_code = 0
    for pr in prs:
        number = pr.get("number") if isinstance(pr, dict) else None
        head_sha = ((pr.get("head") or {}).get("sha") if isinstance(pr, dict) else None)
        if not isinstance(head_sha, str) or not head_sha:
            continue

        try:
            statuses = api.pages(f"/commits/{head_sha}/statuses")
        except Unavailable:
            emit(f"PR #{number} の status を取得できないため fail closed でスキップします。")
            exit_code = 2
            continue

        decision = decide(now, pr, statuses, repository)
        if decision["action"] != "dispatch":
            continue

        try:
            fresh, _ = api.get(f"/pulls/{decision['pr_number']}")
        except Unavailable:
            emit(f"PR #{number} の再確認に失敗したため dispatch しません。")
            exit_code = 2
            continue

        fresh_head = (fresh.get("head") or {}).get("sha") if isinstance(fresh, dict) else None
        if fresh_head != decision["target_sha"]:
            emit(f"PR #{number} の head が dispatch 直前に変わったため、古い SHA の review は開始しません。")
            continue

        try:
            fresh_statuses = api.pages(f"/commits/{fresh_head}/statuses")
        except Unavailable:
            exit_code = 2
            continue
        if decide(now, fresh, fresh_statuses, repository)["action"] != "dispatch":
            continue

        try:
            api.post(
                "/actions/workflows/codex-review.yml/dispatches",
                {
                    "ref": "main",
                    "inputs": {
                        "pr_number": str(decision["pr_number"]),
                        "target_sha": decision["target_sha"],
                    },
                },
            )
        except Unavailable:
            emit(f"PR #{number} の Codex review dispatch に失敗しました。")
            exit_code = 2
            continue

        emit(f"PR #{number} head {decision['target_sha'][:12]} の trusted CI 成功を受けて Codex review を要求しました。")

    return exit_code


def main() -> int:
    def emit(message: str) -> None:
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%H:%M:%S UTC")
        print(f"[codex-review-reconcile {stamp}] {message}", flush=True)

    try:
        repository = os.environ["REPOSITORY"]
        api = GitHubAPI(repository, os.environ["GH_TOKEN"])
    except (KeyError, Unavailable):
        emit("設定を確認できないため終了します。")
        return 2

    return run(api, repository, dt.datetime.now(dt.timezone.utc), emit)


if __name__ == "__main__":
    raise SystemExit(main())
