"""Regression tests for the trusted-CI -> Codex review reconciliation script.

The central scenario is the hane#79 stall: `/implement` opens a same-repository
Pull Request with GITHUB_TOKEN, trusted CI (`hane/trusted-ci-generation`)
finishes successfully for the exact head SHA, but `codex-review.yml`'s
`pull_request_target` chain never fires because GitHub does not run further
workflows for events generated by `GITHUB_TOKEN`. `decide()` is the pure
policy that hane#80 introduces to recover from that gap; `run()` is the thin
GitHub API loop around it.
"""
import datetime as dt
import importlib.util
from pathlib import Path
import unittest
from unittest.mock import patch

PATH = Path(__file__).resolve().parents[1] / "scripts" / "codex_review_reconcile.py"
spec = importlib.util.spec_from_file_location("codex_review_reconcile", PATH)
reconcile = importlib.util.module_from_spec(spec)
spec.loader.exec_module(reconcile)

REPO = "hide212131/hane"
SHA = "0d8a6ca2c5c0290072b797de95c7f0d5d9a6d807"
SHORT = SHA[:12]
NOW = dt.datetime(2026, 9, 7, 12, 0, 0, tzinfo=dt.timezone.utc)


def pr(number=79, state="open", draft=False, author="claude[bot]", head_repo=REPO, sha=SHA):
    return {
        "number": number,
        "state": state,
        "draft": draft,
        "user": {"login": author},
        "head": {"sha": sha, "repo": {"full_name": head_repo}},
    }


def status(context, state, description="", created_at="2026-09-07T11:00:00Z", status_id=1):
    return {"context": context, "state": state, "description": description, "created_at": created_at, "id": status_id}


def passing_ci_statuses(generation_id="123-1"):
    return [
        status("hane/trusted-ci-generation", "success", f"Trusted CI generation {generation_id} passed", status_id=3),
        status("cargo test / clippy (macos-latest)", "success", "Trusted CI passed", status_id=1),
        status("cargo test / clippy (windows-latest)", "success", "Trusted CI passed", status_id=2),
    ]


class DecideTests(unittest.TestCase):
    def test_pr79_stall_is_recovered(self):
        """Exact reproduction of the hane#79 condition: CI is exact-head
        terminal success and no hane/codex-review status exists at all."""
        decision = reconcile.decide(NOW, pr(), passing_ci_statuses(), REPO)
        self.assertEqual(decision, {"action": "dispatch", "pr_number": 79, "target_sha": SHA})

    def test_pending_ci_does_not_start_review(self):
        statuses = [status("hane/trusted-ci-generation", "pending", "Trusted CI generation 123-1")]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "ci-not-terminal")

    def test_failed_ci_does_not_start_review(self):
        statuses = [status("hane/trusted-ci-generation", "failure", "Trusted CI generation 123-1 failed")]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "ci-not-terminal")

    def test_stale_or_malformed_generation_marker_does_not_start_review(self):
        for description in ("", "Trusted CI generation 123-1", "garbage", "Trusted CI generation 123-1 incomplete"):
            with self.subTest(description=description):
                statuses = [status("hane/trusted-ci-generation", "success", description)]
                self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "ci-not-terminal")

    def test_generation_success_without_matching_platform_success_is_not_terminal(self):
        statuses = [
            status("hane/trusted-ci-generation", "success", "Trusted CI generation 123-1 passed", status_id=3),
            status("cargo test / clippy (macos-latest)", "success", status_id=1),
            status("cargo test / clippy (windows-latest)", "failure", status_id=2),
        ]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "ci-not-terminal")

    def test_missing_platform_status_is_not_terminal(self):
        statuses = [status("hane/trusted-ci-generation", "success", "Trusted CI generation 123-1 passed")]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "ci-not-terminal")

    def test_already_clean_review_is_not_duplicated(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "success", f"Codex review clean for {SHORT}", status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "already-reviewed")

    def test_already_findings_review_is_not_duplicated(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "failure", f"Codex findings for {SHORT}", status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "already-reviewed")

    def test_recent_pending_review_is_not_duplicated(self):
        created = (NOW - dt.timedelta(seconds=60)).isoformat().replace("+00:00", "Z")
        statuses = passing_ci_statuses() + [status("hane/codex-review", "pending", f"Codex review pending for {SHORT}", created_at=created, status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "in-flight")

    def test_pending_review_with_unparsable_timestamp_fails_closed(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "pending", f"Codex review pending for {SHORT}", created_at="not-a-date", status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["reason"], "in-flight")

    def test_stale_pending_review_is_reclaimed(self):
        created = (NOW - dt.timedelta(seconds=7200)).isoformat().replace("+00:00", "Z")
        statuses = passing_ci_statuses() + [status("hane/codex-review", "pending", f"Codex review pending for {SHORT}", created_at=created, status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["action"], "dispatch")

    def test_controller_failure_is_retried(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "error", f"Codex review controller failed for {SHORT}", status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["action"], "dispatch")

    def test_review_for_a_different_old_sha_is_not_reused(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "success", "Codex review clean for aaaaaaaaaaaa", status_id=4)]
        self.assertEqual(reconcile.decide(NOW, pr(), statuses, REPO)["action"], "dispatch")

    def test_draft_pr_is_skipped(self):
        self.assertEqual(reconcile.decide(NOW, pr(draft=True), passing_ci_statuses(), REPO)["reason"], "not-eligible")

    def test_closed_pr_is_skipped(self):
        self.assertEqual(reconcile.decide(NOW, pr(state="closed"), passing_ci_statuses(), REPO)["reason"], "not-eligible")

    def test_fork_pr_is_skipped(self):
        self.assertEqual(reconcile.decide(NOW, pr(head_repo="someone-else/hane"), passing_ci_statuses(), REPO)["reason"], "not-eligible")

    def test_untrusted_author_is_skipped(self):
        self.assertEqual(reconcile.decide(NOW, pr(author="rando"), passing_ci_statuses(), REPO)["reason"], "not-eligible")

    def test_repository_owner_pushes_are_eligible(self):
        decision = reconcile.decide(NOW, pr(author="hide212131"), passing_ci_statuses(), REPO)
        self.assertEqual(decision["action"], "dispatch")

    def test_malformed_pr_shapes_fail_closed(self):
        for bad in (None, {}, {"state": "open", "draft": False, "user": {"login": "claude[bot]"}, "head": {}}):
            with self.subTest(bad=bad):
                self.assertEqual(reconcile.decide(NOW, bad, passing_ci_statuses(), REPO)["action"], "skip")

    def test_non_list_statuses_fail_closed(self):
        self.assertEqual(reconcile.decide(NOW, pr(), None, REPO)["reason"], "ci-not-terminal")

    def test_fresh_head_after_a_fix_gets_its_own_fresh_decision(self):
        new_sha = "1111222233334444555566667777888899990000"
        decision = reconcile.decide(NOW, pr(sha=new_sha), passing_ci_statuses(), REPO)
        self.assertEqual(decision, {"action": "dispatch", "pr_number": 79, "target_sha": new_sha})


class FakeAPI:
    def __init__(self, prs, statuses_by_sha, fresh_by_number=None, post_fails=False, pages_fail=False):
        self.prs = prs
        self.statuses_by_sha = statuses_by_sha
        self.fresh_by_number = fresh_by_number or {}
        self.post_fails = post_fails
        self.pages_fail = pages_fail
        self.posts = []

    def pages(self, suffix, key=None):
        if self.pages_fail:
            raise reconcile.Unavailable()
        if suffix.startswith("/pulls?state=open"):
            return self.prs
        for sha, statuses in self.statuses_by_sha.items():
            if suffix.startswith(f"/commits/{sha}/statuses"):
                return statuses
        raise reconcile.Unavailable()

    def get(self, suffix):
        for number, fresh in self.fresh_by_number.items():
            if suffix == f"/pulls/{number}":
                return fresh, False
        raise reconcile.Unavailable()

    def post(self, suffix, payload):
        if self.post_fails:
            raise reconcile.Unavailable()
        self.posts.append((suffix, payload))


class RunTests(unittest.TestCase):
    def setUp(self):
        self.lines = []

    def emit(self, message):
        self.lines.append(message)

    def test_pr79_scenario_dispatches_exactly_once(self):
        api = FakeAPI([pr()], {SHA: passing_ci_statuses()}, fresh_by_number={79: pr()})
        result = reconcile.run(api, REPO, NOW, self.emit)
        self.assertEqual(result, 0)
        self.assertEqual(api.posts, [
            ("/actions/workflows/codex-review.yml/dispatches",
             {"ref": "main", "inputs": {"pr_number": "79", "target_sha": SHA}}),
        ])
        self.assertTrue(any("要求しました" in line for line in self.lines))

    def test_head_moved_between_snapshot_and_dispatch_is_not_reviewed(self):
        moved = pr(sha="9999999999999999999999999999999999999999")
        api = FakeAPI([pr()], {SHA: passing_ci_statuses()}, fresh_by_number={79: moved})
        result = reconcile.run(api, REPO, NOW, self.emit)
        self.assertEqual(result, 0)
        self.assertEqual(api.posts, [])
        self.assertTrue(any("head が dispatch 直前に変わった" in line for line in self.lines))

    def test_already_reviewed_pr_is_not_redispatched(self):
        statuses = passing_ci_statuses() + [status("hane/codex-review", "success", f"Codex review clean for {SHORT}", status_id=4)]
        api = FakeAPI([pr()], {SHA: statuses})
        result = reconcile.run(api, REPO, NOW, self.emit)
        self.assertEqual(result, 0)
        self.assertEqual(api.posts, [])

    def test_listing_failure_is_fail_closed(self):
        api = FakeAPI([], {}, pages_fail=True)
        self.assertEqual(reconcile.run(api, REPO, NOW, self.emit), 2)

    def test_status_lookup_failure_for_one_pr_does_not_block_others(self):
        other_sha = "abcabcabcabcabcabcabcabcabcabcabcabcabc"
        api = FakeAPI(
            [pr(number=79, sha=SHA), pr(number=80, sha=other_sha)],
            {other_sha: passing_ci_statuses()},
            fresh_by_number={80: pr(number=80, sha=other_sha)},
        )
        result = reconcile.run(api, REPO, NOW, self.emit)
        self.assertEqual(result, 2)
        self.assertEqual(len(api.posts), 1)
        self.assertEqual(api.posts[0][1]["inputs"]["target_sha"], other_sha)

    def test_dispatch_failure_is_reported_and_fail_closed(self):
        api = FakeAPI([pr()], {SHA: passing_ci_statuses()}, fresh_by_number={79: pr()}, post_fails=True)
        result = reconcile.run(api, REPO, NOW, self.emit)
        self.assertEqual(result, 2)
        self.assertTrue(any("dispatch に失敗" in line for line in self.lines))


class GitHubAPITests(unittest.TestCase):
    def test_invalid_repository_or_missing_token_fail_closed(self):
        for repo, token in (("../bad", "fake"), ("a/b?x", "fake"), (REPO, "")):
            with self.subTest(repo=repo, token=token):
                with self.assertRaises(reconcile.Unavailable):
                    reconcile.GitHubAPI(repo, token)

    def test_pages_stops_after_five_pages_without_silent_truncation(self):
        api = reconcile.GitHubAPI(REPO, "fake")
        with patch.object(api, "get", return_value=([1], True)) as get:
            with self.assertRaises(reconcile.Unavailable):
                api.pages("/pulls?state=open")
            self.assertEqual(get.call_count, 5)

    def test_no_redirect(self):
        self.assertIsNone(reconcile.NoRedirect().redirect_request(None, None, 302, "", {}, "https://attacker"))


if __name__ == "__main__":
    unittest.main()
